### ISSUE TITLE
Chemical ontology completeness for Natural Products

### ISSUE THREAD

**Issue by Adafede** [rwst/yaccl#1]
Maybe have a look at: https://github.com/mwang87/NP-Classifier/blob/master/Classifier/dict/index_v1.json for NP-related chemical classes that could be added to the [ontology](https://www.wikidata.org/wiki/User:SCIdude/Modeling#Chemical_ontology).

For example: https://www.wikidata.org/wiki/Q15438649 or https://www.wikidata.org/wiki/Q669514

Any way to proceed best? Are the *allowed references* really restricted to the one mentioned?

**Comment by rwst** [comment]
No restrictions. Just add to the list at https://www.wikidata.org/wiki/Wikidata:WikiProject_Chemistry/Chemical_classification.
